ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_type TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS company TEXT;
CREATE INDEX IF NOT EXISTS users_email_lower ON users (lower(email)) WHERE email IS NOT NULL AND email <> '';
