-- Same gap as 013 for team, but for the shop catalog: product.model.js
-- has no JS-level fallback the way settings.model.js does, so production
-- was showing a genuinely empty Shop page and homepage "Shop favourites"
-- with nothing masking it. Same 8 products, same ids, same ascending
-- created_at-by-array-position trick as 013 so ordering matches local.
INSERT INTO app_records (collection, id, data, created_at) VALUES
  ('products', 'shade-guide', '{"id": "shade-guide", "name": "VITA Classical Shade Guide", "category": "Chairside kit", "price": 28, "sku": "CK-SHADE-01", "stock": 14, "active": true, "desc": "A1–D4 reference tabs for accurate shade calls before you scan.", "specs": [{"label": "Tabs", "value": "16 shades, A1–D4"}, {"label": "Standard", "value": "VITA Classical"}, {"label": "Sterilisation", "value": "Autoclavable to 134°C"}]}'::jsonb, TIMESTAMPTZ '2024-01-01 00:00:00' + interval '0 seconds'),
  ('products', 'retraction-kit', '{"id": "retraction-kit", "name": "Retraction Cord Kit", "category": "Chairside kit", "price": 19, "sku": "CK-CORD-02", "stock": 22, "active": true, "desc": "Assorted-gauge cord for the margin photos our protocol asks for.", "specs": [{"label": "Gauges", "value": "#000, #00, #0, #1"}, {"label": "Material", "value": "Knitted, non-impregnated"}, {"label": "Length", "value": "4 × 244 cm"}]}'::jsonb, TIMESTAMPTZ '2024-01-01 00:00:00' + interval '1 seconds'),
  ('products', 'impression-trays', '{"id": "impression-trays", "name": "Digital Impression Tray Set", "category": "Chairside kit", "price": 34, "sku": "CK-TRAY-03", "stock": 9, "active": true, "desc": "Sized trays to steady a scan on difficult arches.", "specs": [{"label": "Sizes", "value": "S / M / L, upper & lower"}, {"label": "Reusable", "value": "Yes — autoclavable"}]}'::jsonb, TIMESTAMPTZ '2024-01-01 00:00:00' + interval '2 seconds'),
  ('products', 'temp-kit', '{"id": "temp-kit", "name": "Temporary Crown & Bridge Kit", "category": "Chairside kit", "price": 42, "sku": "CK-TEMP-04", "stock": 6, "active": true, "desc": "Interim coverage while a case is in production.", "specs": [{"label": "Shade", "value": "A2 bis-acryl"}, {"label": "Yield", "value": "~40 units per cartridge"}, {"label": "Set time", "value": "2:30 min"}]}'::jsonb, TIMESTAMPTZ '2024-01-01 00:00:00' + interval '3 seconds'),
  ('products', 'whitening-kit', '{"id": "whitening-kit", "name": "Take-Home Whitening Kit", "category": "Patient retail", "price": 25, "sku": "PR-WHT-01", "stock": 30, "active": true, "desc": "Dentist-recommended kit to finish whitening comfortably at home.", "specs": [{"label": "Gel", "value": "16% carbamide peroxide"}, {"label": "Syringes", "value": "4 × 3 ml"}, {"label": "Trays", "value": "Thermoform, upper & lower"}]}'::jsonb, TIMESTAMPTZ '2024-01-01 00:00:00' + interval '4 seconds'),
  ('products', 'retainer-case', '{"id": "retainer-case", "name": "Ceram Care Retainer Case", "category": "Patient retail", "price": 6, "sku": "PR-CASE-02", "stock": 48, "active": true, "desc": "A proper home for retainers and night guards between visits.", "specs": [{"label": "Material", "value": "Vented ABS shell"}, {"label": "Colours", "value": "Plum, bone, charcoal"}]}'::jsonb, TIMESTAMPTZ '2024-01-01 00:00:00' + interval '5 seconds'),
  ('products', 'sonic-toothbrush', '{"id": "sonic-toothbrush", "name": "Ceram Care Sonic Toothbrush", "category": "Patient retail", "price": 32, "sku": "PR-BRSH-03", "stock": 17, "active": true, "desc": "Gentle on veneers and crowns — the brush we recommend after treatment.", "specs": [{"label": "Speed", "value": "31,000 strokes/min"}, {"label": "Battery", "value": "30 days per charge"}, {"label": "Modes", "value": "Clean, Sensitive, Polish"}]}'::jsonb, TIMESTAMPTZ '2024-01-01 00:00:00' + interval '6 seconds'),
  ('products', 'bite-paste', '{"id": "bite-paste", "name": "Bite Registration Paste", "category": "Chairside kit", "price": 22, "sku": "CK-BITE-05", "stock": 11, "active": true, "desc": "Fast-set paste for an accurate bite record with every impression.", "specs": [{"label": "Base", "value": "A-silicone"}, {"label": "Set time", "value": "45 s intra-oral"}, {"label": "Shore hardness", "value": "D 32"}]}'::jsonb, TIMESTAMPTZ '2024-01-01 00:00:00' + interval '7 seconds')
ON CONFLICT (collection, id) DO NOTHING;
